language: minimal
dist: focal

addons:
  apt: &apt_packages
    - lua-busted
    - neovim
    - scdoc
  homebrew:
    - neovim
    - scdoc
    - luarocks

matrix:
  include:
    - os: linux
    - os: linux
      env: UNSTABLE=true
      addons:
        apt:
          source: { sourceline: 'ppa:neovim-ppa/unstable' }
          packages: *apt_packages
    - os: freebsd
      addons:
        pkg:
          - neovim
          - scdoc
          - lua51-luarocks
      env: BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
    - os: osx
      # Older versions have trouble with homebrew.  When the osx builds start
      # to fail again or take to long try updating this first.
      osx_image: xcode12.5
      env: BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
  allow_failures:
    - os: linux
      env: UNSTABLE=true

before_install: |
  case "$TRAVIS_OS_NAME" in
    freebsd) luarocks51 --local install busted;;
    osx)     luarocks   --local install busted;;
  esac

install: |
  case "$TRAVIS_OS_NAME" in
    freebsd) gmake install PREFIX=$HOME/.local;;
    *)       make  install PREFIX=$HOME/.local;;
  esac

script: |
  case "$TRAVIS_OS_NAME" in
    freebsd) gmake test BUSTED="$BUSTED";;
    *)       make  test BUSTED="${BUSTED:-busted}";;
  esac
